# Site settings
theme: minimal-mistakes-jekyll
locale: "en"
title: "Aadit Kamat"
name: "Aadit Kamat"
description: "Powered by Jekyll and minimal-mistakes theme"
repository: "aaditkamat/aaditkamat.com"

author: 
  name: "Aadit Kamat"
  avatar: "/static/profile.img"
  bio: "MSISOM at Warrington School of Business"
  location: "Gainesville, FL"
  github: "aaditkamat"
  linkedin: "aaditkamat"
  twitter: "aaditkamat"
  instagram: "aadit_kamat"

# Conversion
markdown: kramdown

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


defaults:
  # _posts
  - scope:
      path: "posts/"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

include: 
  - _pages