/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Aadit Kamat",
  "tagline": "Personal Website",
  "url": "https://aaditkamat.com",
  "baseUrl": "/",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "img/profile.jpg",
  "organizationName": "aaditkamat",
  "projectName": "aaditkamat.com",
  "scripts": [
    {
      "src": "https://instant.page/5.1.0",
      "async": true,
      "type": "module",
      "integrity": "sha384-by67kQnR+pyfy8yWP4kPO12fHKRLHZPfEsiSXR8u2IKcTdxD805MGUXBzVPnkLHw"
    },
    {
      "src": "https://utteranc.es/client.js",
      "repo": "aaditkamat/aaditkamat.com",
      "issueTerm": "url",
      "label": "enhancement",
      "theme": "github-light",
      "crossorigin": "anonymous",
      "async": true
    }
  ],
  "themeConfig": {
    "metadata": [
      {
        "name": "description",
        "content": "Hello world, this is Aadit. Welcome to my 🏠 on the internet."
      },
      {
        "name": "robots",
        "content": "index, follow"
      }
    ],
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "navbar": {
      "title": "Aadit Kamat",
      "items": [
        {
          "to": "/about-me",
          "label": "About Me",
          "position": "left"
        },
        {
          "to": "/bookmarks",
          "label": "Bookmarks",
          "position": "left"
        },
        {
          "to": "/calendar",
          "label": "Calendar",
          "position": "left"
        },
        {
          "to": "/podcasts",
          "label": "Podcasts",
          "position": "left"
        },
        {
          "to": "/projects",
          "label": "Projects",
          "position": "left"
        },
        {
          "to": "/resume",
          "label": "Résumé",
          "position": "left"
        },
        {
          "to": "/tools",
          "label": "Tools",
          "position": "left"
        },
        {
          "href": "https://github.com/aaditkamat/aaditkamat.com",
          "position": "right",
          "className": "navbar-icon navbar-icon-github",
          "aria-label": "GitHub repository"
        },
        {
          "href": "https://twitter.com/aaditkamat",
          "position": "right",
          "className": "navbar-icon navbar-icon-twitter",
          "aria-label": "Twitter page"
        },
        {
          "href": "https://www.instagram.com/aadit_kamat",
          "position": "right",
          "className": "navbar-icon navbar-icon-instagram",
          "aria-label": "Instagram page"
        },
        {
          "href": "https://aaditkamat.medium.com",
          "position": "right",
          "className": "navbar-icon navbar-icon-medium",
          "aria-label": "Medium page"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [],
      "copyright": "Copyright © 2020 - 2023 Aadit Kamat. Built with Docusaurus."
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "prism": {
      "additionalLanguages": [],
      "theme": {
        "plain": {
          "color": "#bfc7d5",
          "backgroundColor": "#292d3e"
        },
        "styles": [
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(105, 112, 152)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "inserted"
            ],
            "style": {
              "color": "rgb(195, 232, 141)"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "rgb(247, 140, 108)"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function"
            ],
            "style": {
              "color": "rgb(130, 170, 255)"
            }
          },
          {
            "types": [
              "punctuation",
              "selector"
            ],
            "style": {
              "color": "rgb(199, 146, 234)"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "rgb(191, 199, 213)"
            }
          },
          {
            "types": [
              "class-name",
              "attr-name"
            ],
            "style": {
              "color": "rgb(255, 203, 107)"
            }
          },
          {
            "types": [
              "tag",
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 114)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "rgb(137, 221, 255)"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "rgb(255, 88, 116)"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "doctype"
            ],
            "style": {
              "color": "rgb(199, 146, 234)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "rgb(178, 204, 214)"
            }
          },
          {
            "types": [
              "url"
            ],
            "style": {
              "color": "rgb(221, 221, 221)"
            }
          }
        ]
      },
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "theme": {
          "customCss": "/workspaces/aaditkamat.com/src/css/custom.css"
        }
      }
    ]
  ],
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "path": "i18n",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "headTags": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false
  }
};
